# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "NuGet" # See documentation for possible values
    directory: "/NVs.OccupancySensor.API" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "NuGet" # See documentation for possible values
    directory: "/NVs.OccupancySensor.CV" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "NuGet" # See documentation for possible values
    directory: "/NVs.OccupancySensor.CV.Tests" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "NuGet" # See documentation for possible values
    directory: "/NVs.OccupancySensor.API.Tests" # Location of package manifests
    schedule:
      interval: "weekly"
