name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - ./**/*
  pull_request:
    branches: [ master ]
    paths-ignore:
      - ./**/*
jobs:

  build:

    runs-on: [self-hosted, linux, arm]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile
