name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - readme.md
      - .github/**
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile
